Repository thecaffeinecoders/Investify, pull requests merged in 2018-11, with the labels that each got.

#23 adding simpleRegression lib to the app
  app/build.gradle
  app/src/main/java/android/example/com/investify/SecondActivity.java
Labels: enhancement

#41 re push the branch
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/android/example/com/investify/ThirdActivity.java
  app/src/main/java/android/example/com/investify/WebViewActivity.java
  app/src/main/res/layout/activity_third.xml
  app/src/main/res/layout/activity_web_view.xml
Labels: Layout (XML)

#44 fixing CompaniesLogos Res
  app/src/main/AndroidManifest.xml
  app/src/main/java/android/example/com/investify/RecyclerViewAdapter.java
  app/src/main/res/font/amiri_italic.xml
  app/src/main/res/layout/layout_listitem.xml
  app/src/main/res/values/preloaded_fonts.xml
Labels: Feature
